This code extracts data from the air4thai

http://air4thai.pcd.go.th/webV2/history/api/data.php?stationID=03t&param=PM25&type=hr&sdate=2019-01-17&edate=2019-01-17

In [307]:
import requests
from datetime import date, datetime, timedelta
import pandas as pd

In [433]:
station_list = [
    '02t', '03t', '05t', '08t', '10t',
    '11t', '12t', '13t', '14t', '16t', '17t', '18t', '19t',
    '20t', '21t', '22t', '24t', '25t', '26t', '27t', '28t', '29t',
    '30t', '31t', '32t', '33t', '34t', '35t', '36t', '37t', '38t', '39t',
    '40t', '41t', '42t', '43t', '44t', '46t', '47t',
    '50t', '52t', '53t', '54t', '57t', '58t', '59t',
    '60t', '61t', '62t', '63t', '67t', '68t', '69t',
    '70t', '71t', '72t', '73t', '74t', '75t', '76t', '77t', '79t',
    '80t'
]

measured_list = ['PM25', 'PM10', 'O3', 'CO', 'NO2', 'SO2']
#measured_list = ['SO2']



ytd = str(date.today()-timedelta(1))    # get yesterday's date

meas_dat = pd.DataFrame()



for meas in measured_list :             # loop over each measurement
    
    pm = []
    tm = []
    dt = []
    stn= []

    for stn_i in station_list :             # loop over each station
        
        
        url = 'http://air4thai.pcd.go.th/webV2/history/api/data.php?stationID=' + stn_i + '&param=' + meas + '&type=hr&sdate=' + ytd + '&edate=' + ytd
    
        data = requests.request("GET", url).json()

        
        if data['stations'] == []:
            val_data = data
            
            for each in list(range(0,24)):
                
                DT_obj = datetime.strptime(ytd, '%Y-%m-%d')
                #print(each)
                DT_obj = DT_obj.replace(hour=each)
                #print(DT_obj)
                DT_str = DT_obj.strftime('%Y-%m-%d %H:%M:%S')
                
                time_dat = DT_str
                 
                date_str = time_dat[0:10]
                time_str = time_dat[11:]
                
                pm.append(None)
                tm.append(time_str)
                dt.append(date_str)
                stn.append(stn_i)
                
        else :
            val_data = data['stations'][0]['data']


            for each in val_data :          # loop over each time stamp
                time_dat = each['DATETIMEDATA']
                date_str = time_dat[0:10]
                time_str = time_dat[11:]
                
                tm.append(time_str)
                dt.append(date_str)

                val_dat  = each[meas]
                if val_dat == '-' :
                    val_dat = None
                pm.append(val_dat)
                stn.append(stn_i)
                
                
    meas_dat['station'] = stn
    
    meas_dat['date'] = dt
    meas_dat['time'] = tm
    meas_dat[meas] = pm

In [434]:
meas_dat

     station        date      time  PM25   PM10    O3    CO   NO2  SO2
0        02t  2019-01-24  00:00:00   NaN    NaN   NaN   NaN   NaN  NaN
1        02t  2019-01-24  01:00:00   NaN    NaN   NaN   NaN   NaN  NaN
2        02t  2019-01-24  02:00:00   NaN    NaN   NaN   NaN   NaN  NaN
3        02t  2019-01-24  03:00:00   NaN    NaN   NaN   NaN   NaN  NaN
4        02t  2019-01-24  04:00:00   NaN    NaN   NaN   NaN   NaN  NaN
5        02t  2019-01-24  05:00:00   NaN    NaN   NaN   NaN   NaN  NaN
6        02t  2019-01-24  06:00:00   NaN    NaN   NaN   NaN   NaN  NaN
7        02t  2019-01-24  07:00:00   NaN    NaN   NaN   NaN   NaN  NaN
8        02t  2019-01-24  08:00:00   NaN    NaN   NaN   NaN   NaN  NaN
9        02t  2019-01-24  09:00:00   NaN    NaN   NaN   NaN   NaN  NaN
10       02t  2019-01-24  10:00:00   NaN    NaN   NaN   NaN   NaN  NaN
11       02t  2019-01-24  11:00:00   NaN    NaN   NaN   NaN   NaN  NaN
12       02t  2019-01-24  12:00:00   NaN    NaN   NaN   NaN   NaN  NaN
13       02t  2019-01-24  13:00:00   NaN    NaN   NaN   NaN   NaN  NaN
14       02t  2019-01-24  14:00:00   NaN    NaN   NaN   NaN   NaN  NaN
15       02t  2019-01-24  15:00:00   NaN    NaN   NaN   NaN   NaN  NaN
16       02t  2019-01-24  16:00:00   NaN    NaN   NaN   NaN   NaN  NaN
17       02t  2019-01-24  17:00:00   NaN    NaN   NaN   NaN   NaN  NaN
18       02t  2019-01-24  18:00:00   NaN    NaN   NaN   NaN   NaN  NaN
19       02t  2019-01-24  19:00:00   NaN    NaN   NaN   NaN   NaN  NaN
20       02t  2019-01-24  20:00:00   NaN    NaN   NaN   NaN   NaN  NaN
21       02t  2019-01-24  21:00:00   NaN    NaN   NaN   NaN   NaN  NaN
22       02t  2019-01-24  22:00:00   NaN    NaN   NaN   NaN   NaN  NaN
23       02t  2019-01-24  23:00:00   NaN    NaN   NaN   NaN   NaN  NaN
24       03t  2019-01-24  00:00:00  65.0  107.0   3.0  2.15  64.0  NaN
25       03t  2019-01-24  01:00:00  62.0   95.0   3.0  1.92  54.0  NaN
26       03t  2019-01-24  02:00:00  58.0   85.0   NaN   NaN   NaN  NaN
27       03t  2019-01-24  03:00:00  58.0    NaN   3.0  1.87  52.0  NaN
28       03t  2019-01-24  04:00:00  60.0    NaN   5.0  1.69  44.0  NaN
29       03t  2019-01-24  05:00:00  59.0    NaN   2.0  1.73  47.0  NaN
...      ...         ...       ...   ...    ...   ...   ...   ...  ...
1482     79t  2019-01-24  18:00:00  43.0   59.0  38.0  0.68  26.0  1.0
1483     79t  2019-01-24  19:00:00  49.0   78.0   NaN   NaN   NaN  NaN
1484     79t  2019-01-24  20:00:00  58.0   89.0  13.0  1.29  47.0  2.0
1485     79t  2019-01-24  21:00:00  69.0   99.0   4.0  1.56  46.0  2.0
1486     79t  2019-01-24  22:00:00  78.0  105.0  15.0  1.21  31.0  2.0
1487     79t  2019-01-24  23:00:00  84.0  101.0  20.0  0.93  19.0  2.0
1488     80t  2019-01-24  00:00:00  14.0   17.0  38.0  0.60   1.0  NaN
1489     80t  2019-01-24  01:00:00  13.0   16.0  39.0  0.58   1.0  NaN
1490     80t  2019-01-24  02:00:00  12.0   20.0  33.0  0.60   2.0  NaN
1491     80t  2019-01-24  03:00:00  14.0   21.0  35.0  0.59   1.0  NaN
1492     80t  2019-01-24  04:00:00  13.0   24.0  41.0  0.60   1.0  NaN
1493     80t  2019-01-24  05:00:00  13.0   28.0  39.0  0.62   3.0  NaN
1494     80t  2019-01-24  06:00:00  15.0   30.0  37.0  0.64   4.0  NaN
1495     80t  2019-01-24  07:00:00  16.0   40.0  28.0  0.84  14.0  1.0
1496     80t  2019-01-24  08:00:00  18.0   47.0  35.0  0.74  14.0  1.0
1497     80t  2019-01-24  09:00:00  20.0   54.0  43.0  0.65   4.0  NaN
1498     80t  2019-01-24  10:00:00  21.0   62.0  45.0  0.63   3.0  1.0
1499     80t  2019-01-24  11:00:00  22.0   61.0  47.0  0.64   4.0  1.0
1500     80t  2019-01-24  12:00:00  22.0   56.0  49.0  0.63   3.0  1.0
1501     80t  2019-01-24  13:00:00  23.0   52.0  49.0  0.64   3.0  1.0
1502     80t  2019-01-24  14:00:00  23.0   47.0  51.0  0.65   5.0  1.0
1503     80t  2019-01-24  15:00:00  25.0   30.0  53.0  0.69   5.0  1.0
1504     80t  2019-01-24  16:00:00  24.0   26.0  56.0  0.73   5.0  1.0
1505     80t  2019-01-24  17:00:00  26.0   28.0  58.0  0.76   5.0  1.0
1506     80t  2019-01-24  18:00:00  27.0   29.0  53.0  0.75   6.0  1.0
1507     80t  2019-01-24  19:00:00  26.0   32.0  48.0  0.73   5.0  1.0
1508     80t  2019-01-24  20:00:00  24.0   34.0   NaN   NaN   NaN  NaN
1509     80t  2019-01-24  21:00:00  22.0   32.0  50.0  0.67   3.0  NaN
1510     80t  2019-01-24  22:00:00  21.0   34.0  48.0  0.66   3.0  1.0
1511     80t  2019-01-24  23:00:00  20.0   38.0  49.0  0.66   2.0  1.0

[1512 rows x 9 columns]

In [435]:
meas_dat.to_csv('~/Documents/pm25/pm_data/pm_data_'+ytd+'.csv', encoding='utf-8')